<a href="https://colab.research.google.com/github/MarshaGomez/DNN-Sketches-image-analysis/blob/main/Code/MIRCV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Setting up the project


In [ ]:
import numpy as np
from numpy.linalg import norm

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)

Mounted at /content/gdrive


In [ ]:
zip_path = '/content/gdrive/Shareddrives/COMPUTER_VISION/MIM_zipped.zip'
!cp "{zip_path}" .
!unzip -q MIM_zipped.zip
!rm MIM_zipped.zip


### LSH Class


In [ ]:
# def singleton(class_):
#     instances = {}
#     def getinstance(*args, **kwargs):
#         if class_ not in instances:
#             instances[class_] = class_(*args, **kwargs)
#         return instances[class_]
#     return getinstance

# @singleton
# per adesso è più scomodo che utile averlo come singleton
import time

class LSH:
  def __init__(self, feature_dim, g = 10, h = 20, w = 4, differentiate_g = False, bitwise_hash = False):
    """
    We have to find a way to load the stored index if exists or initialize the 
    initial structure
    """
    self._index = {}
    if bitwise_hash:
      # self.x = np.random.randn(g, h, feature_dim) # non sembra richieda una distribuzione normale
      self.x = np.random.normal(size=(g, h, feature_dim))
    else:
      self.x = np.random.normal(size=(g, h, feature_dim))
    self.w = np.ones((g, h, 1)) * w
    self.b = np.random.rand(g, h, 1) * w
    self.differentiate_g = differentiate_g # se 2 g inseriscono nello stesso bucket, possiamo decidere se differenziarle o meno
    self.bitwise_hash = bitwise_hash # another way to create h (h will be only 0 o 1)

  def _hash(self, features):
    """
    crea l'hash di più cose contemporaeamente si aspetta un array composto dalle features una sotta l'altra (linguaggio super matematico)
    """
    # g = np.trunc((np.dot(p, self.x) + self.b) / self.w)
    #g = np.trunc((np.dot(self.x, p) + self.b) / self.w) questo funziona con 1
    # g = np.transpose(np.trunc(((np.dot(self.x, p.T) + self.b) / self.w)), (0,2,1)) miglior modo di vederlo
    if self.bitwise_hash:
      return (np.transpose(np.dot(self.x, features.T), (0,2,1)) > 0).astype(int).astype(str)
    return np.transpose(np.trunc(((np.dot(self.x, features.T) + self.b) / self.w)), (0,2,1)).astype(int).astype(str)

  def insert(self, features, ids, labels):
    """
    Insert new data, ci aspettiamo un array d
    """
    g = self._hash(features)
    assert features.shape[0] == len(ids), "mismatch between ids length and features"
    assert len(labels) == len(ids), "mismatch between ids length and labels"
    
    number_elements = len(ids)
    i = 0
    print("hash calculated")
    print(g.shape)
    g_index = -1
    for g_function in g:
      start_inner_for = time.time()
      g_index += 1
      for row in g_function:
        if i % 10000 == 0:
          start = time.time()
        
        if self.differentiate_g: # assicura che ogni g inserisca in un bucket differente
          bucket_id = str(g_index) + '-' + ','.join(row)
        else: 
          bucket_id = ','.join(row)
        
        if i % 10000 == 0:
            end = time.time()
            print(f'join {end - start}')
        if not bucket_id in self._index:
          # self._index[bucket_id] = { 'features': np.array([features[i % number_elements]]), 'ids': np.array([ids[i % number_elements]]), 'labels': np.array([labels[i % number_elements]])}
          self._index[bucket_id] = { 'features': [features[i % number_elements]], 'ids': [ids[i % number_elements]], 'labels': [labels[i % number_elements]]}
          if i % 10000 == 0:
            end = time.time()
            print(f'not in bucket {end - start}')
        else:
          if ids[i % number_elements] in self._index[bucket_id]['ids']:
            # print("duplicate")
            continue
          if i % 10000 == 0:
            end = time.time()
            print(f'checking duplicates {end - start}')
          # print("collision inserted")
          # self._index[bucket_id]['features'] = np.vstack((self._index[bucket_id]['features'], features[i % number_elements]))
          self._index[bucket_id]['features'].append(features[i % number_elements])
          # self._index[bucket_id]['ids'] = np.vstack((self._index[bucket_id]['ids'], ids[i % number_elements]))
          self._index[bucket_id]['ids'].append(ids[i % number_elements])
          # self._index[bucket_id]['labels'] = np.vstack((self._index[bucket_id]['labels'], labels[i % number_elements]))
          self._index[bucket_id]['labels'].append(labels[i % number_elements])
          if i % 10000 == 0:
            end = time.time()
            print(f'stacking {end - start}')
        i += 1
        assert i > 0, 'out of bound'
      end_inner_for = time.time()
      print(f'inner for time: {end_inner_for - start_inner_for}')
    
    for bucket_id in self._index:
      self._index[bucket_id]['features'] = np.array(self._index[bucket_id]['features'])
      print(self._index[bucket_id]['features'].shape)
      self._index[bucket_id]['ids'] = np.array(self._index[bucket_id]['ids'], )
      self._index[bucket_id]['labels'] = np.array(self._index[bucket_id]['labels'])
      

  def query(self, features, top_k, mode = 'euclidean', return_cost = False):
    """
    Query the data
    """
    g = self._hash(np.array([features]))
    i = 0
    k = None
    top_k += 1 # per far ritornare k e non k - 1
    cost = 0
    g_index = -1
    assert mode in ['similarity', 'euclidean'], "mode must be similarity or euclidean"
    for g_function in g:
      g_index += 1
      for row in g_function:
        if self.differentiate_g: # assicura che ogni g inserisca in un bucket differente
          bucket_id = str(g_index) + '-' + ','.join(row)
        else: 
          bucket_id = ','.join(row)
        print(bucket_id)
        if bucket_id in self._index:
          # posso avere duplicati perchè se i punti vengono inseriti in più bucket, posso avere duplicati
          # quindi devo eliminarli
          # l'ho messo qua fuori che il controllo duplicati è uguale per tutte e due le distanze
          # print(f'bucket {bucket_id}')
          if k is not None:
            # print("duplicate")
            duplicate_index = np.isin(self._index[bucket_id]['ids'], k['ids'])
            if duplicate_index.all():
              continue; # se sono tutti duplicati non ha senso contare nulla
            bucket = {}
            bucket['ids'] = self._index[bucket_id]['ids'][~duplicate_index] # prendo quelli che non sono duplicati
            # print(duplicate_index)
            # print(self._index[bucket_id]['features'])
            bucket['features'] = self._index[bucket_id]['features'][~duplicate_index.flatten()] # each duplicate index must delete a row of features
            bucket['labels'] = self._index[bucket_id]['labels'][~duplicate_index]
          else:
            bucket = self._index[bucket_id]
        
          if mode == 'euclidean':
            # print(bucket['features'].shape)
            dist = norm(bucket['features'] - np.array(features), axis=1)
            print(f'dist shape {dist.shape} and dist size {dist.size}')
            cost += dist.size
            if k is None:
              idx_partitioned = np.argpartition(dist, top_k - 1 if dist.shape[0] - 1 > top_k - 1 else dist.shape[0] - 1)
              if dist.shape[0] - 1 > top_k - 1:  
                  idx_partitioned = idx_partitioned[:top_k - 1]
              k = {}
              # qua è più comodo avere array 1- dimensionali
              k['ids'] = bucket['ids'][idx_partitioned].flatten()
              k['labels'] = bucket['labels'][idx_partitioned].flatten()
              k['distances'] = dist[idx_partitioned]
              continue
            # https://stackoverflow.com/questions/10337533/a-fast-way-to-find-the-largest-n-elements-in-an-numpy-array
            # argpartition sembra essere incredibilmente veloce
            # ma non ordina completamente, ordina solo rispetto un punto, nel senso
            # io gli sto dicendo butta quelli più piccoli di k da una parte e quelli più grandi all'altra, ma non sto ordinando
            if k['distances'].shape[0] < top_k:
                # print((k['distances'].shape, dist.shape))
                distances = np.concatenate((k['distances'], dist))
                # print((k['ids'].shape, bucket['ids'].shape))
                # print(k['ids'])
                # print(bucket['ids'])
                ids = np.concatenate((k['ids'], bucket['ids']))
                # print((k['labels'].shape, bucket['labels'].shape))
                labels = np.concatenate((k['labels'], bucket['labels']))
                idx_sorted = np.argpartition(distances, top_k - 1 if distances.shape[0] - 1 > top_k else distances.shape[0] - 1)
                if distances.shape[0] - 1 > top_k - 1:  
                  idx_sorted = idx_sorted[:top_k - 1]
                k['ids'] = ids[idx_sorted]
                k['labels'] = labels[idx_sorted]
                k['distances'] = distances[idx_sorted]
                # print(f'k = {k}')
                continue

            idx = dist < np.max(k['distances'])
            # print(f"idx = {idx}")
            if np.any(idx):
              distances = np.concatenate((k['distances'], dist[idx]))
              ids = np.concatenate((k['ids'], bucket['ids'][idx]))
              labels = np.concatenate((k['labels'], bucket['labels'][idx]))
              idx_sorted = np.argpartition(distances, top_k - 1 if distances.shape[0] - 1 > top_k else distances.shape[0] - 1)
              if distances.shape[0] - 1 > top_k - 1:  
                  idx_sorted = idx_sorted[:top_k - 1]
              k['ids'] = ids[idx_sorted]
              k['labels'] = labels[idx_sorted]
              k['distances'] = distances[idx_sorted]

          else:
            # print(bucket['features'].shape)
            sim = np.sum(bucket['features'] * np.array(features), axis=1) / (norm(bucket['features'], axis=1) * norm(np.array([features]), axis=1))
            print(f'sim shape {sim.shape} and sim size {sim.size}')
            cost += sim.size
            if k is None:
              idx_partitioned = np.argpartition(sim, -(top_k - 1) if sim.shape[0] - 1 > top_k - 1 else sim.shape[0] - 1)
              if sim.shape[0] - 1 > top_k - 1:  
                idx_partitioned = idx_partitioned[-(top_k - 1):]
              k = {}
              # qua è più comodo avere array 1- dimensionali
              k['ids'] = bucket['ids'][idx_partitioned].flatten()
              k['labels'] = bucket['labels'][idx_partitioned].flatten()
              k['similarities'] = sim[idx_partitioned]
              continue
            # https://stackoverflow.com/questions/10337533/a-fast-way-to-find-the-largest-n-elements-in-an-numpy-array
            # argpartition sembra essere incredibilmente veloce
            # ma non ordina completamente, ordina solo rispetto un punto, nel senso
            # io gli sto dicendo butta quelli più piccoli di k da una parte e quelli più grandi all'altra, ma non sto ordinando
            if k['similarities'].shape[0] < top_k:
                # print((k['similarities'].shape, sim.shape))
                similarities = np.concatenate((k['similarities'], sim))
                # print((k['ids'].shape, bucket['ids'].shape))
                # print(k['ids'])
                # print(bucket['ids'])
                ids = np.concatenate((k['ids'], bucket['ids']))
                # print((k['labels'].shape, bucket['labels'].shape))
                labels = np.concatenate((k['labels'], bucket['labels']))
                idx_sorted = np.argpartition(similarities, -(top_k - 1) if similarities.shape[0] - 1 > top_k - 1 else similarities.shape[0] - 1)
                if similarities.shape[0] - 1 > top_k - 1:  
                  idx_sorted = idx_sorted[-(top_k - 1):]
                k['ids'] = ids[idx_sorted]
                k['labels'] = labels[idx_sorted]
                k['similarities'] = similarities[idx_sorted]
                # print(f'k = {k}')
                continue

            idx = sim > np.min(k['similarities'])
            # print(f"idx = {idx}")
            if np.any(idx):
              similarities = np.concatenate((k['similarities'], sim[idx]))
              ids = np.concatenate((k['ids'], bucket['ids'][idx]))
              labels = np.concatenate((k['labels'], bucket['labels'][idx]))
              idx_sorted = np.argpartition(similarities, -(top_k - 1) if similarities.shape[0] - 1 > top_k - 1 else similarities.shape[0] - 1)
              if similarities.shape[0] - 1 > top_k - 1:  
                idx_sorted = idx_sorted[-(top_k - 1):]
              k['ids'] = ids[idx_sorted]
              k['labels'] = labels[idx_sorted]
              k['similarities'] = similarities[idx_sorted]
        i += 1
    # ora ordino totalmente i risultati
    if k is None:
      return {} #zero result
    if mode == 'euclidean':
      idx_sorted = np.argsort(k['distances'])
      idx_sorted = idx_sorted[:top_k - 1 if k['distances'].shape[0] - 1 > top_k else k['distances'].shape[0]]
      k['distances'] = k['distances'][idx_sorted]
      k['ids'] = k['ids'][idx_sorted]
      k['labels'] = k['labels'][idx_sorted]
      if return_cost:
        return (k, cost)
      return k
    idx_sorted = np.argsort(k['similarities'])[::-1]
    idx_sorted = idx_sorted[:top_k - 1 if k['similarities'].shape[0] - 1 > top_k else k['similarities'].shape[0]]
    k['similarities'] = k['similarities'][idx_sorted]
    k['ids'] = k['ids'][idx_sorted]
    k['labels'] = k['labels'][idx_sorted]
    if return_cost:
      return (k, cost)
    return k

  def store(self):
    pass


In [ ]:
a = np.array([4, 3, 2, 1, 0])
a[np.argpartition(a,0)]

array([0, 3, 2, 1, 4])

In [ ]:
class NO_INDEX:
  def __init__(self):
    self.features = None
    self.ids = None
    self.labels = None

  def insert(self, features, ids, labels):
    assert features.shape[0] == len(ids), "mismatch between ids length and features"
    assert len(labels) == len(ids), "mismatch between ids length and labels"
    self.features = features
    self.ids = ids
    self.labels = labels
  
  def query(self, features, top_k, mode = 'euclidean', return_cost = False):
    assert mode in ['similarity', 'euclidean'], "mode must be similarity or euclidean"
    top_k += 1
    if mode == 'euclidean':
      dist = norm(self.features - np.array(features), axis=1)
      idx_partitioned = np.argpartition(dist, top_k - 1 if dist.shape[0] - 1 > top_k - 1 else dist.shape[0] - 1)
      k = {}
      # qua è più comodo avere array 1- dimensionali
      k['ids'] = self.ids[idx_partitioned].flatten()[:top_k - 1 if dist.shape[0] - 1 > top_k - 1 else dist.shape[0]]
      k['labels'] = self.labels[idx_partitioned].flatten()[:top_k - 1 if dist.shape[0] - 1 > top_k - 1 else dist.shape[0]]
      k['distances'] = dist[idx_partitioned][:top_k - 1 if dist.shape[0] - 1 > top_k - 1 else dist.shape[0]]
      
      idx_sorted = np.argsort(k['distances'])
      idx_sorted = idx_sorted
      k['distances'] = k['distances'][idx_sorted]
      k['ids'] = k['ids'][idx_sorted]
      k['labels'] = k['labels'][idx_sorted]
      if return_cost:
        return (k, dist.size)
      return k
    sim = np.sum(self.features * np.array(features), axis=1) / (norm(self.features, axis=1) * norm(np.array([features]), axis=1))
    idx_partitioned = np.argpartition(sim, -(top_k - 1) if sim.shape[0] - 1 > top_k - 1 else sim.shape[0] - 1)
    print(sim.shape[0])
    k = {}
    # qua è più comodo avere array 1- dimensionali
    if sim.shape[0] - 1 > top_k - 1:  
      idx_partitioned = idx_partitioned[-(top_k - 1):]

    k['ids'] = self.ids[idx_partitioned].flatten()
    k['labels'] = self.labels[idx_partitioned].flatten()
    k['similarities'] = sim[idx_partitioned]
    idx_sorted = np.argsort(k['similarities'])[::-1]
    idx_sorted = idx_sorted
    k['similarities'] = k['similarities'][idx_sorted]
    k['ids'] = k['ids'][idx_sorted]
    k['labels'] = k['labels'][idx_sorted]
    if return_cost:
      return (k, sim.size)
    return k
    

In [ ]:
#### TESTING PURPOSE
print('"Base LSH"')
index = LSH(feature_dim= 2, g= 2, h=2)
print('x=')
print(index.x)
print('w=')
print(index.w)
print('b=')
print(index.b)
print('ps =')
print(np.array([[1,1], [1.1, 1.2], [1.4, 1.44], [3, 4]]))
print('insert')
index.insert(
     np.array([[1,1], [1.1, 1.2], [1.4, 1.44], [3, 4]]), 
     np.array(['uno', 'due', 'tre','quattro']),
     np.array([0,0,1,1])
     )
print(index._index)
print('query euclidean')
print(index.query([1,1], 4, return_cost=True))
print('query similarity')
print(index.query([1,1], 4, mode='similarity', return_cost=True))
print(index)


print('"Differentiate g LSH"')
index = LSH(feature_dim= 2, g= 2, h=2, differentiate_g=True)
print('x=')
print(index.x)
print('w=')
print(index.w)
print('b=')
print(index.b)
print('ps =')
print(np.array([[1,1], [1.1, 1.2], [1.4, 1.44], [3, 4]]))
print('insert')
index.insert(
     np.array([[1,1], [1.1, 1.2], [1.4, 1.44], [3, 4]]), 
     np.array(['uno', 'due', 'tre','quattro']),
     np.array([0,0,1,1])
     )
print(index._index)
print('query')
print(index.query([1,1], 4))
print(index)


print('"bitwise hash LSH"')
index = LSH(feature_dim= 2, g=2, h=2, bitwise_hash=True)
print('x=')
print(index.x)
print('w=')
print(index.w)
print('b=')
print(index.b)
print('ps =')
print(np.array([[1,1], [1.1, 1.2], [1.4, 1.44], [3, 4]]))
print('insert')
index.insert(
     np.array([[1,1], [1.1, 1.2], [1.4, 1.44], [3, 4]]), 
     np.array(['uno', 'due', 'tre','quattro']),
     np.array([0,0,1,1])
     )
print(index._index)
print('query')
print(index.query([1,1], 4))
print(index)

print('NO INDEX')
index = NO_INDEX()
print(np.array([[1,1], [1.1, 1.2], [1.4, 1.44], [3, 4]]))
print('insert')
index.insert(
     np.array([[1,1], [1.1, 1.2], [1.4, 1.44], [3, 4]]), 
     np.array(['uno', 'due', 'tre','quattro']),
     np.array([0,0,1,1])
     )
print('query euclidean')
print(index.query([1,1], 4, return_cost=True))
print('query similarity')
print(index.query([1,1], 4, mode='similarity', return_cost=True))
print(index)


"Base LSH"
x=
[[[-0.18783918  0.75334016]
  [ 0.12190565 -0.14548194]]

 [[-0.40398417  0.01557776]
  [-1.83078914 -0.86391799]]]
w=
[[[4.]
  [4.]]

 [[4.]
  [4.]]]
b=
[[[2.63705556]
  [0.37983413]]

 [[1.12068416]
  [2.0950663 ]]]
ps =
[[1.   1.  ]
 [1.1  1.2 ]
 [1.4  1.44]
 [3.   4.  ]]
insert
hash calculated
(2, 4, 2)
join 1.5020370483398438e-05
not in bucket 5.8650970458984375e-05
inner for time: 0.00010347366333007812
inner for time: 2.09808349609375e-05
(3, 2)
(1, 2)
(1, 2)
{'0,0': {'features': array([[1.  , 1.  ],
       [1.1 , 1.2 ],
       [1.4 , 1.44]]), 'ids': array(['uno', 'due', 'tre'], dtype='<U3'), 'labels': array([0, 0, 1])}, '1,0': {'features': array([[3., 4.]]), 'ids': array(['quattro'], dtype='<U7'), 'labels': array([1])}, '0,-1': {'features': array([[1., 1.]]), 'ids': array(['uno'], dtype='<U3'), 'labels': array([0])}}
query euclidean
0,0
dist shape (3,) and dist size 3
0,0
({'ids': array(['uno', 'due', 'tre'], dtype='<U3'), 'labels': array([0, 0, 1]), 'distances': 

### Loading images DATA


In [ ]:
import os 
from IPython.display import display
from ipywidgets import Image

#data loading
# reading from unzipped
BASE_DIR = "/content/content/gdrive/Shareddrives/COMPUTER_VISION/MIRCV"
# FILELIST_PATH = BASE_DIR + "/filelist.txt"
SKETCHES_DIR = BASE_DIR + "/sketches/png"
MIRFLICKR_DIR = BASE_DIR + "/mirflickr/mirflickr25k"

#print(FILELIST_PATH)

#num_folders = os.listdir(SKETCHES_DIR)
#print(num_folders)

In [ ]:
# sketch image displaying 
filename = "airplane/1.png"
image1 = os.path.join(SKETCHES_DIR, filename)
display(Image.from_file(image1, width=300, height=400))

Image(value=b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x04W\x00\x00\x04W\x08\x00\x00\x00\x00\x105\xd1!\x00\…

In [ ]:
# mirflickr image displaying 
filename = "png/im20.jpg"
image1 = os.path.join(MIRFLICKR_DIR, filename)
display(Image.from_file(image1, width=300, height=400))

Image(value=b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01\x01,\x01,\x00\x00\xff\xe2\x0cXICC_PROFILE\x00\x01\x…

In [ ]:
IMG_HEIGHT = 229
IMG_WIDTH = 229
INPUT_SHAPE = (IMG_WIDTH, IMG_HEIGHT, 3)
BATCH_SIZE = 512

In [ ]:
from tensorflow.keras.preprocessing import image_dataset_from_directory
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.inception_v3 import preprocess_input
#yields batches of images from the subdirectories 
#found in the sketches directory [class_0 ... class_250]
#together with class labels.

#images normalization 
sketches_datagen = ImageDataGenerator(preprocessing_function=preprocess_input)
mirflickr_datagen = ImageDataGenerator(preprocessing_function=preprocess_input)

sketches_generator = sketches_datagen.flow_from_directory(
        # This is the target directory
        SKETCHES_DIR,
        shuffle=False,
        target_size=(IMG_HEIGHT, IMG_WIDTH),
        batch_size=BATCH_SIZE)

mirflickr_generator = mirflickr_datagen.flow_from_directory(
        # This is the target directory
        MIRFLICKR_DIR,
        shuffle=False,
        target_size=(IMG_HEIGHT, IMG_WIDTH),
        batch_size=BATCH_SIZE)


# unique, counts = np.unique(sketches_generator.classes, return_counts=True)
# labels_dict = dict(zip(unique, counts))
# print(labels_dict)

Found 20000 images belonging to 250 classes.
Found 25000 images belonging to 1 classes.


### Loading DNN for features extraction

In [ ]:
#loading Inception DNN
from tensorflow.keras.applications.inception_v3 import InceptionV3

conv_base = InceptionV3(weights='imagenet',
                  include_top=False,
                  input_shape=INPUT_SHAPE,
                  pooling='avg')

conv_base.summary()

Model: "inception_v3"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 229, 229, 3) 0                                            
__________________________________________________________________________________________________
conv2d (Conv2D)                 (None, 114, 114, 32) 864         input_1[0][0]                    
__________________________________________________________________________________________________
batch_normalization (BatchNorma (None, 114, 114, 32) 96          conv2d[0][0]                     
__________________________________________________________________________________________________
activation (Activation)         (None, 114, 114, 32) 0           batch_normalization[0][0]        
_______________________________________________________________________________________

In [ ]:
#Extracting features using the pretrained convolutional base 

def extract_features(extractor, generator, sample_count, dim=2048):
  features = np.zeros((sample_count, dim)) #extractor output shape 
  i = 0
  for inputs_batch, labels_batch in generator:
    print([np.where(r==1)[0][0] for r in labels_batch])
    start = time.time()
    features_batch = extractor.predict(inputs_batch)
    print(f'predict = {time.time() - start}')
    start = time.time()
    if (i + 1) * BATCH_SIZE > sample_count:
      features[i * BATCH_SIZE : sample_count , :] = features_batch
    else:
      features[i * BATCH_SIZE : (i + 1) * BATCH_SIZE, : ] = features_batch
    i += 1
    if i * BATCH_SIZE >= sample_count:
      break
    print(f'assign = {time.time() - start}')
  
  return features


In [ ]:
sketches_features = extract_features(conv_base, sketches_generator, 20000)
mirflickr_features = extract_features(conv_base, mirflickr_generator, 25000)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 

In [ ]:
print(sketches_features.shape)
print(mirflickr_features.shape)
print(sketches_features[0])
print()
print(mirflickr_features[0])
print(sketches_features[0].nbytes)
print(mirflickr_features[0].nbytes)

(20000, 2048)
(25000, 2048)
[0.78158373 0.3547062  0.07907477 ... 0.14706215 0.         0.37109551]

[1.41843808 0.78591108 0.9991073  ... 1.24422574 1.79479325 0.25287843]
16384
16384


In [ ]:
sketches_features[0,0]

0.7815837264060974

In [ ]:
all_features = np.vstack((sketches_features, mirflickr_features))
lsh_base = LSH(feature_dim = all_features[0].shape[0], g=5, h=1)


In [ ]:
lsh_base.insert(np.vstack((sketches_features, mirflickr_features)), 
                np.concatenate((sketches_generator.filenames, mirflickr_generator.filenames)), 
                np.concatenate((sketches_generator.labels, np.array([250] * mirflickr_features.shape[0]))))

hash calculated
(5, 45000, 1)
join 2.956390380859375e-05
not in bucket 7.128715515136719e-05
join 2.384185791015625e-06
checking duplicates 9.870529174804688e-05
stacking 0.00013065338134765625
join 2.384185791015625e-06
checking duplicates 9.465217590332031e-05
stacking 0.00012946128845214844
join 2.384185791015625e-06
checking duplicates 0.0001266002655029297
stacking 0.0001590251922607422
join 2.384185791015625e-06
checking duplicates 0.0001220703125
stacking 0.00015211105346679688
inner for time: 1.1818130016326904
join 2.384185791015625e-06
checking duplicates 0.00014138221740722656
stacking 0.00017333030700683594
join 3.337860107421875e-06
checking duplicates 0.0002701282501220703
stacking 0.0009310245513916016
join 3.337860107421875e-06
checking duplicates 0.00019502639770507812
stacking 0.000255584716796875
join 4.291534423828125e-06
checking duplicates 0.0002999305725097656
stacking 0.0003619194030761719
inner for time: 3.327036142349243
join 3.0994415283203125e-06
checking du

In [ ]:
start = time.time()
query_result_ed = lsh_base.query(sketches_features[0], 80, return_cost = True)
end = time.time()
print(f'query time {end - start}')
query_result_sim = lsh_base.query(sketches_features[0], 80, mode='similarity', return_cost = True)

7
dist shape (8152,) and dist size 8152
6
dist shape (9154,) and dist size 9154
-8
dist shape (4421,) and dist size 4421
-9
dist shape (3667,) and dist size 3667
7
dist shape (8120,) and dist size 8120
query time 0.43428802490234375
7
sim shape (8152,) and sim size 8152
6
sim shape (9144,) and sim size 9144
-8
sim shape (4421,) and sim size 4421
-9
sim shape (3668,) and sim size 3668
7
sim shape (8112,) and sim size 8112


In [ ]:
print(query_result_ed)
print(query_result_sim)

({'ids': array(['airplane/1.png', 'ship/14915.png', 'bread/2460.png',
       'airplane/74.png', 'lighter/9805.png', 'tablelamp/17327.png',
       'cake/3105.png', 'sea turtle/14569.png', 'arm/414.png',
       'hat/8058.png', 'tractor/18352.png', 'tractor/18388.png',
       'bulldozer/2614.png', 'shark/14786.png', 'floor lamp/6735.png',
       'mouth/10909.png', 'blimp/1892.png', 'squirrel/16217.png',
       'head-phones/8235.png', 'bee/1413.png', 'ship/14959.png',
       'airplane/12.png', 'bulldozer/2628.png', 'couch/4673.png',
       'sheep/14828.png', 'trombone/18690.png', 'shark/14744.png',
       'mouth/10881.png', 'snowboard/15538.png', 'parrot/11814.png',
       'hot-dog/8661.png', 'suitcase/16698.png', 'sea turtle/14582.png',
       'tree/18608.png', 'santa claus/14013.png', 'tractor/18397.png',
       'parrot/11828.png', 'bee/1369.png', 'truck/18848.png',
       'couch/4671.png', 'giraffe/7437.png', 'hamburger/7717.png',
       'sailboat/13940.png', 'mouse (animal)/10803.png',

In [ ]:
no_index_base = NO_INDEX()
no_index_base.insert(np.vstack((sketches_features, mirflickr_features)), 
                np.concatenate((sketches_generator.filenames, mirflickr_generator.filenames)), 
                np.concatenate((sketches_generator.labels, np.array([250] * mirflickr_features.shape[0]))))
start = time.time()
query_result_ed_no_index = no_index_base.query(sketches_features[0], 80, return_cost = True)
end = time.time()
print(f'query time {end - start}')
query_result_sim_no_index = no_index_base.query(sketches_features[0], 80, mode='similarity', return_cost = True)
print(query_result_ed_no_index)
print(query_result_sim_no_index)
print(query_result_sim_no_index[0]['ids'].shape)

query time 1.7094576358795166
45000
({'ids': array(['airplane/1.png', 'airplane/49.png', 'ship/14915.png',
       'bread/2460.png', 'wheelbarrow/19552.png', 'airplane/74.png',
       'lighter/9805.png', 'tablelamp/17327.png', 'cake/3105.png',
       'hamburger/7709.png', 'arm/440.png', 'sea turtle/14569.png',
       'arm/414.png', 'hat/8058.png', 'tractor/18352.png',
       'submarine/16594.png', 'crown/5049.png', 'tractor/18388.png',
       'leaf/9608.png', 'bulldozer/2614.png', 'shark/14786.png',
       'helicopter/8382.png', 'flying saucer/7001.png',
       'floor lamp/6735.png', 'mouth/10909.png', 'blimp/1892.png',
       'pumpkin/13191.png', 'squirrel/16217.png', 'head-phones/8235.png',
       'rainbow/13543.png', 'tv/19008.png', 'rollerblades/13803.png',
       'bee/1413.png', 'ship/14959.png', 'airplane/12.png',
       'bulldozer/2628.png', 'rainbow/13553.png', 'couch/4673.png',
       'sheep/14828.png', 'trombone/18690.png', 'shark/14744.png',
       'mouth/10881.png', 'arm/441

In [ ]:
all_features = np.vstack((sketches_features, mirflickr_features))
lsh_bitwise = LSH(feature_dim = all_features[0].shape[0], g=5, h=1, bitwise_hash=True)
lsh_bitwise.insert(np.vstack((sketches_features, mirflickr_features)), 
                np.concatenate((sketches_generator.filenames, mirflickr_generator.filenames)), 
                np.concatenate((sketches_generator.labels, np.array([250] * mirflickr_features.shape[0]))))
start = time.time()
query_result_ed_bitwise = lsh_bitwise.query(sketches_features[0], 80, return_cost = True)
end = time.time()
print(f'query time {end - start}')
query_result_sim_bitwise = lsh_bitwise.query(sketches_features[0], 80, mode='similarity', return_cost = True)
print(query_result_ed_bitwise)
print(query_result_sim_bitwise)

Streaming output truncated to the last 5000 lines.
join 3.337860107421875e-06
join 2.6226043701171875e-06
join 3.337860107421875e-06
join 8.344650268554688e-06
join 2.86102294921875e-06
join 7.152557373046875e-06
join 4.0531158447265625e-06
join 3.337860107421875e-06
join 3.0994415283203125e-06
join 3.337860107421875e-06
join 3.0994415283203125e-06
join 3.0994415283203125e-06
join 8.106231689453125e-06
join 3.814697265625e-06
join 2.6226043701171875e-06
join 3.5762786865234375e-06
join 3.0994415283203125e-06
join 3.0994415283203125e-06
join 3.0994415283203125e-06
join 3.0994415283203125e-06
join 2.86102294921875e-06
join 3.0994415283203125e-06
join 3.337860107421875e-06
join 2.86102294921875e-06
join 3.0994415283203125e-06
join 2.6226043701171875e-06
join 3.0994415283203125e-06
join 2.86102294921875e-06
join 2.86102294921875e-06
join 3.0994415283203125e-06
join 2.86102294921875e-06
join 3.0994415283203125e-06
join 8.344650268554688e-06
join 3.5762786865234375e-06
join 9.059906005859375

In [ ]:
def compare(a, b):
  for comp in zip(a, b):
    if comp[0] != comp[1]:
      print(comp)
      return False
  return True

In [ ]:
del lsh_bitwise

### Fine tuning with classification

In [ ]:
%tensorflow_version 2.x
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras import models
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report
from keras.callbacks import EarlyStopping, ModelCheckpoint
import numpy as np
from keras.models import Model
from tensorflow.keras.applications.inception_v3 import InceptionV3
from tensorflow.keras.applications.inception_v3 import preprocess_input

In [ ]:
MODEL_PATH = "/content/gdrive/Shareddrives/COMPUTER_VISION/models"

In [ ]:
inception = InceptionV3(weights='imagenet',
                  include_top=False,
                  input_shape=INPUT_SHAPE)
inception.summary()

Model: "inception_v3"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 229, 229, 3) 0                                            
__________________________________________________________________________________________________
conv2d (Conv2D)                 (None, 114, 114, 32) 864         input_1[0][0]                    
__________________________________________________________________________________________________
batch_normalization (BatchNorma (None, 114, 114, 32) 96          conv2d[0][0]                     
__________________________________________________________________________________________________
activation (Activation)         (None, 114, 114, 32) 0           batch_normalization[0][0]        
_______________________________________________________________________________________

In [ ]:
train_datagen = ImageDataGenerator(preprocessing_function=preprocess_input,
    validation_split=0.1,
    zoom_range=0.1,
    rotation_range=180,
    vertical_flip = True,
    horizontal_flip = True
    ) # set validation split


train_generator = train_datagen.flow_from_directory(
    SKETCHES_DIR,
    shuffle=True,
    # All images will be resized to 150x150
    target_size=(IMG_HEIGHT, IMG_WIDTH),
    batch_size=BATCH_SIZE,
    subset='training') # set as training data

validation_generator = train_datagen.flow_from_directory(
    SKETCHES_DIR,
    shuffle=True,
    # All images will be resized to 150x150
    target_size=(IMG_HEIGHT, IMG_WIDTH),
    batch_size=BATCH_SIZE,
    subset='validation') 

inception = InceptionV3(weights='imagenet',
                  include_top=False,
                  pooling='avg',
                  input_shape=INPUT_SHAPE)

set_trainable = False
for layer in inception.layers:
  print(layer.name)
  if layer.name == 'mixed9':
    print('ok')
    set_trainable = True
  layer.trainable = set_trainable


model_classification = keras.models.Sequential()
model_classification.add(inception)
model_classification.add(layers.Dropout(0.5))
model_classification.add(layers.Dense(250, activation='softmax'))
model_classification.compile(loss='categorical_crossentropy',
              # optimizer=keras.optimizers.RMSprop(lr=2e-5),
              optimizer=keras.optimizers.Adam(),
              metrics=['acc'])
model_classification.summary()


model_checkpoint = ModelCheckpoint('checkpoint.h5', save_best_only=True, save_weights_only=True, verbose=1)
callback = tf.keras.callbacks.EarlyStopping(monitor='val_acc', patience=10)


history = model_classification.fit(
  train_generator,
  steps_per_epoch = 20000 * 0.9 // BATCH_SIZE,
  epochs=20,
  validation_data = validation_generator,
  validation_steps =  20000 * 0.1 // BATCH_SIZE,
  callbacks = [callback, model_checkpoint]
  )
model_classification.load_weights('checkpoint.h5')
models.save_model(model_classification, os.path.join(MODEL_PATH, 'inception_finetuning_classification.h5'))

Found 18000 images belonging to 250 classes.
Found 2000 images belonging to 250 classes.
input_3
conv2d_188
batch_normalization_188
activation_188
conv2d_189
batch_normalization_189
activation_189
conv2d_190
batch_normalization_190
activation_190
max_pooling2d_8
conv2d_191
batch_normalization_191
activation_191
conv2d_192
batch_normalization_192
activation_192
max_pooling2d_9
conv2d_196
batch_normalization_196
activation_196
conv2d_194
conv2d_197
batch_normalization_194
batch_normalization_197
activation_194
activation_197
average_pooling2d_18
conv2d_193
conv2d_195
conv2d_198
conv2d_199
batch_normalization_193
batch_normalization_195
batch_normalization_198
batch_normalization_199
activation_193
activation_195
activation_198
activation_199
mixed0
conv2d_203
batch_normalization_203
activation_203
conv2d_201
conv2d_204
batch_normalization_201
batch_normalization_204
activation_201
activation_204
average_pooling2d_19
conv2d_200
conv2d_202
conv2d_205
conv2d_206
batch_normalization_200
batc

In [ ]:
loaded = models.load_model(os.path.join(MODEL_PATH, 'inception_finetuning_classification.h5'))
finetuned_extactor = Model(loaded.input, loaded.layers[-2].output)
finetuned_extactor.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
inception_v3_input (InputLay [(None, 229, 229, 3)]     0         
_________________________________________________________________
inception_v3 (Functional)    (None, 2048)              21802784  
_________________________________________________________________
dropout (Dropout)            (None, 2048)              0         
Total params: 21,802,784
Trainable params: 6,073,536
Non-trainable params: 15,729,248
_________________________________________________________________


In [ ]:
import time
sketches_features_finetuned = extract_features(finetuned_extactor, sketches_generator, 20000)
mirflickr_features_finetuned = extract_features(finetuned_extactor, mirflickr_generator, 25000)
all_features = np.vstack((sketches_features_finetuned, mirflickr_features_finetuned))

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 

In [ ]:
no_index_finetuned = NO_INDEX()
no_index_finetuned.insert(np.vstack((sketches_features_finetuned, mirflickr_features_finetuned)), 
                np.concatenate((sketches_generator.filenames, mirflickr_generator.filenames)), 
                np.concatenate((sketches_generator.labels, np.array([250] * mirflickr_features_finetuned.shape[0]))))

In [ ]:
query_result_ed = no_index_finetuned.query(sketches_features_finetuned[0], 80)
query_result_sim = no_index_finetuned.query(sketches_features_finetuned[0], 80, mode='similarity')

45000


In [ ]:
print(sketches_features_finetuned.shape)
print(mirflickr_features_finetuned.shape)

(20000, 2048)
(25000, 2048)


In [ ]:
print(query_result_ed)
print(query_result_sim)

{'ids': array(['airplane/1.png', 'submarine/16597.png', 'flying saucer/6979.png',
       'airplane/54.png', 'airplane/44.png', 'ship/14933.png',
       'submarine/16568.png', 'airplane/18.png', 'ship/14927.png',
       'flying saucer/7036.png', 'airplane/53.png', 'airplane/49.png',
       'flying saucer/6999.png', 'flying saucer/7029.png',
       'sailboat/13972.png', 'space shuttle/15812.png', 'airplane/12.png',
       'mushroom/11060.png', 'ship/14923.png', 'submarine/16582.png',
       'pretzel/13102.png', 'ship/14906.png', 'cake/3105.png',
       'flying saucer/7007.png', 'airplane/8.png', 'flying bird/6909.png',
       'hamburger/7717.png', 'crown/5091.png', 'purse/13213.png',
       'ship/14955.png', 'sailboat/13940.png', 'mushroom/11073.png',
       'hamburger/7755.png', 'airplane/56.png',
       'satellite dish/14204.png', 'flying saucer/7014.png',
       'flying saucer/7002.png', 'rollerblades/13803.png',
       'flying saucer/7005.png', 'butterfly/2854.png', 'carrot/3696.png'

### Evaluation

In [ ]:
def average_precision(requested_label, result_labels, n_ground_truth = 80):
  """
  label ricercata, label ottenute, il numero di oggetti che ci sono quella label
  """
  return np.sum((requested_label == result_labels).astype(int) / np.arange(1, result_labels.size + 1)) / n_ground_truth

In [ ]:
query_result_ed = no_index_base.query(sketches_features[0], 80)
query_result_sim = no_index_base.query(sketches_features[0], 80, mode='similarity')
print('euclidean')
print(query_result_ed)
print(average_precision(0, query_result_ed['labels']))
print('similarity')
print(query_result_ed)
print(average_precision(0, query_result_ed['labels']))

In [ ]:
from random import random
def mAP(index, features, n_queries = 500, n_labels = 250, img_per_labels = 80, mode = 'euclidean'):
  sum = 0
  for i in range(n_queries):
    label = i % n_labels
    image_idx = ((i * img_per_labels) + int(random() * img_per_labels)) % (n_labels * img_per_labels)
    # print('QUERY')
    # print('index = ' + str(image_idx))
    # print('label =' + str(label))
    res = index.query(features[image_idx], img_per_labels, mode = mode)
    # print('first label of resultset (must be equal to label) = ' + str(res['labels'][0]))
    assert res['labels'][0] == label, 'deve essere della stessa label'
    sum += average_precision(label, res['labels'])
  return sum / n_queries


In [ ]:
map_value = mAP(no_index_base, sketches_features)
print(map_value)

0.02177244528603028


In [ ]:
mAP(no_index_finetuned, sketches_features_finetuned)

0.026893228948344724

In [ ]:
mAP(no_index_finetuned, sketches_features_finetuned, mode='similarity')

In [ ]:
# try to calculate bucket dispersion
# ritorna la percentuale media, la deviazione standard della classe più popolosa dei bucket,
# ritorna anche il numero di bucket
def bucket_dispersion(index):
  percs = None
  itemsCount = None
  i = 0
  for bucket in index._index:
    i += 1
    _, counts = np.unique(index._index[bucket]['labels'], return_counts=True)
    perc = np.max(counts) / np.sum(counts)
    itemCount = np.sum(counts)
    if percs is None:
      percs = np.array([perc])
      itemsCount = np.array([itemCount])
    else:
      percs = np.concatenate((percs, np.array([perc])))
      itemsCount = np.concatenate((itemsCount, np.array([itemCount])))
  return {
      'perc': {
          'mean': np.mean(percs),
          'deviation': np.std(percs)
      },
      'count': {
          'average': np.mean(itemsCount),
          'deviation': np.std(itemsCount)
      },
      'n_buckets': i,
      'n_items_counting_duplicates': np.sum(itemsCount) # ci sono anche i duplicati
  }
print(bucket_dispersion(lsh_base))
print(bucket_dispersion(lsh_finetuned))
